# Generated by Django 5.1.4 on 2025-01-03 22:51

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.models import User

def add_default_setting(apps, schema_editor):
    Setting = apps.get_model('smdatabase', 'Setting')
    Setting.objects.update_or_create(
        setting_key='legacy_date',
        defaults={'setting_value': '2022-01-01'}
    )
def add_default_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='smkid'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('points', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('studynr', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('points', models.FloatField()),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('setting_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('points', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('studynr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdatabase.member')),
            ],
        ),
        migrations.RunPython(add_default_setting),
        migrations.RunPython(add_default_admin),
    ]
